### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by didib** [oVirt/ovirt-tinycore-linux#2]
IANAL.

IMO including a copy of some license (GPL2, in this case) _without_ any other explanation might be confusing and misleading. I recommend having a slightly-customized version of the recommended notice in a file LICENSE and have the original license file in a file COPYING (as is customary for the GPL, but can be any name).

See also, as an example:

https://github.com/oVirt/ovirt-system-tests/commit/9e47bb13
https://github.com/oVirt/ovirt-system-tests/commit/48652687
https://github.com/oVirt/ovirt-system-tests/commit/803b65a6

**Comment by lveyde** [comment]
Solved in #4
